/* Text to put at the beginning of the generated file. Probably a license. */

#ifndef LIB_RITI_H
#define LIB_RITI_H

/* Generated with cbindgen:0.8.7 */

/* 
 * Warning, this file is autogenerated by cbindgen. Don't modify this manually.
 * Run this command to generate this file: cbindgen --config cbindgen.toml --output include/libriti.h 
 */


#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define IM_COMMIT 1 << 1

#define IM_DEFAULT 0

#define IM_KEY_ACCEPTED 1 << 0

#define IM_NEED_RESET 1 << 3

#define IM_NEED_UPDATE 1 << 2

#define MODIFIER_ALT 1 << 2

#define MODIFIER_CTRL 1 << 1

#define MODIFIER_SHIFT 1 << 0

#define VC_0 11

#define VC_1 2

#define VC_2 3

#define VC_3 4

#define VC_4 5

#define VC_5 6

#define VC_6 7

#define VC_7 8

#define VC_8 9

#define VC_9 10

#define VC_A 41140

#define VC_ALT 56

#define VC_AMPERSAND 65

#define VC_APOSTROPHE 40

#define VC_ASTERISK 66

#define VC_AT 60

#define VC_B 41141

#define VC_BACKSPACE 14

#define VC_BACK_SLASH 43

#define VC_BAR 93

#define VC_BRACE_LEFT 91

#define VC_BRACE_RIGHT 92

#define VC_BRACKET_LEFT 26

#define VC_BRACKET_RIGHT 27

#define VC_C 41142

#define VC_CIRCUM 64

#define VC_COLON 99

#define VC_COMMA 51

#define VC_CONTROL 29

#define VC_D 41143

#define VC_DELETE 3667

#define VC_DOLLAR 62

#define VC_DOWN 57424

#define VC_E 41144

#define VC_END 3663

#define VC_ENTER 28

#define VC_EQUALS 13

#define VC_EXCLAIM 59

#define VC_F 41145

#define VC_G 41146

#define VC_GRAVE 41

#define VC_GREATER 102

#define VC_H 41147

#define VC_HASH 61

#define VC_HOME 3655

#define VC_I 41148

#define VC_INSERT 3666

#define VC_J 41149

#define VC_K 41150

#define VC_KP_0 82

#define VC_KP_1 79

#define VC_KP_2 80

#define VC_KP_3 81

#define VC_KP_4 75

#define VC_KP_5 76

#define VC_KP_6 77

#define VC_KP_7 71

#define VC_KP_8 72

#define VC_KP_9 73

#define VC_KP_ADD 78

#define VC_KP_DECIMAL 83

#define VC_KP_DIVIDE 3637

#define VC_KP_ENTER 3612

#define VC_KP_EQUALS 3597

#define VC_KP_MULTIPLY 55

#define VC_KP_SUBTRACT 74

#define VC_L 41151

#define VC_LEFT 57419

#define VC_LESS 101

#define VC_M 41152

#define VC_MINUS 12

#define VC_N 41153

#define VC_O 41154

#define VC_P 41155

#define VC_PAGE_DOWN 3665

#define VC_PAGE_UP 3657

#define VC_PAREN_LEFT 67

#define VC_PAREN_RIGHT 68

#define VC_PERCENT 63

#define VC_PERIOD 52

#define VC_PLUS 88

#define VC_Q 41156

#define VC_QUESTION 103

#define VC_QUOTE 100

#define VC_R 41157

#define VC_RIGHT 57421

#define VC_S 41158

#define VC_SEMICOLON 39

#define VC_SHIFT 42

#define VC_SLASH 53

#define VC_SPACE 57

#define VC_T 41159

#define VC_TAB 15

#define VC_TILDE 1

#define VC_U 41160

#define VC_UNDERSCORE 87

#define VC_UNKNOWN 70

#define VC_UP 57416

#define VC_V 41161

#define VC_W 41162

#define VC_X 41163

#define VC_Y 41164

#define VC_Z 41165

/*
 Context handle used for libRiti IM APIs
 */
typedef struct RitiContext RitiContext;

/*
 Suggestions which are intend to be shown by the IM's candidate window.
 */
typedef struct Suggestion Suggestion;

void riti_context_free(RitiContext *ptr);

bool riti_context_key_handled(RitiContext *ptr);

RitiContext *riti_context_new(void);

Suggestion riti_get_suggestion_for_key(RitiContext *ptr,
                                       uint16_t key,
                                       uint8_t modifier);

uintptr_t riti_suggestion_get_length(const Suggestion *ptr);

char *const *riti_suggestion_get_suggestions(const Suggestion *ptr);

#endif /* LIB_RITI_H */
